version: '3.9'

services:
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    container_name: nginx-node-rabbit
    restart: always
    volumes:
      - ./client:/var/www
      - ./services/nginx/logs:/var/log/nginx
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5001:80
    networks:
      - network

  rabbitmq:
    build:
      context: services/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-node-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  api:
    build: 
      context: services/server
      dockerfile: Dockerfile
    container_name: api-node-rabbit
    restart: always
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CONTAINER=API
      - SERVER_PORT=3000
      - APP_PATH=/usr/src/app
    networks:
      - network

  worker:
    build: 
      context: services/server
      dockerfile: Dockerfile
    container_name: worker-node-rabbit
    restart: always
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CONTAINER=WORKER
      - SERVER_PORT=3000
      - APP_PATH=/usr/src/app
    networks:
      - network
    depends_on: 
      - rabbitmq
      - api

# volumes:
#   mongo:
#     driver: local

networks:
  network:
    driver: bridge
